version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: finance_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: financeKagurPasszxc
      POSTGRES_DB: finance_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresqldocker-compose down -v

  mongodb:
    image: mongo:latest
    container_name: finance_mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongoPasszxc
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
